getova/webinterface/config/routes.rb
Rails.application.routes.draw do

  resources :tanet_linkedins
  get '/scrape_linkedin' => 'tanet_linkedins#scrape_person'

  resources :tenders

  resources :complus

  post 'fetch_led_company' => 'complus#fetch_led_company'

  resources :tanets

  resources :individual_formats

  get 'companies/run_clustering' => 'companies#run_clustering'
  get 'companies/search/:search' => 'companies#search'
  get 'companies/clustering_visual' => 'companies#get_json_for_d3'

  get 'tanet' => 'tanets#index'
  get 'tanet/:id' => 'tanets#show'

  resources :companies

  resources :representations

  resources :individuals

  root 'individuals#index'

  get 'about' => 'about#index'
  get 'search' => 'search#index'

  get 'individuals/:id/:format' => 'individuals#get_format'

end

getova/webinterface/app/models/tanet.rb
class Tanet < ActiveRecord::Base
end

getova/webinterface/app/controllers/tanets_controller.rb
class TanetsController < ApplicationController
  before_action :set_tanet, only: [:show, :edit, :update, :destroy]

  # GET /tanets
  # GET /tanets.json
  def index
    @tanets = Tanet.all
  end

  # GET /tanets/1
  # GET /tanets/1.json
  def show
  end

  # GET /tanets/new
  def new
    @tanet = Tanet.new
  end

  # GET /tanets/1/edit
  def edit
  end

  # POST /tanets
  # POST /tanets.json
  def create
    @tanet = Tanet.new(tanet_params)

    respond_to do |format|
      if @tanet.save
        format.html { redirect_to @tanet, notice: 'Tanet was successfully created.' }
        format.json { render :show, status: :created, location: @tanet }
      else
        format.html { render :new }
        format.json { render json: @tanet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tanets/1
  # PATCH/PUT /tanets/1.json
  def update
    respond_to do |format|
      if @tanet.update(tanet_params)
        format.html { redirect_to @tanet, notice: 'Tanet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tanet }
      else
        format.html { render :edit }
        format.json { render json: @tanet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tanets/1
  # DELETE /tanets/1.json
  def destroy
    @tanet.destroy
    respond_to do |format|
      format.html { redirect_to tanets_url, notice: 'Tanet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tanet
      @tanet = Tanet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tanet_params
      params.require(:tanet).permit(:data)
    end
end

getova/webinterface/app/helpers/tanets_helper.rb
module TanetsHelper
end

getova/webinterface/app/views/tanets/_form.html.erb
<%= form_for(@tanet) do |f| %>
  <% if @tanet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tanet.errors.count, "error") %> prohibited this tanet from being saved:</h2>

      <ul>
      <% @tanet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br>
    <%= f.text_field :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

getova/webinterface/app/views/tanets/edit.html.erb
<h1>Editing tanet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tanet %> |
<%= link_to 'Back', tanets_path %>

getova/webinterface/app/views/tanets/index.html.erb
<h1>Tanet Use-Case</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tanets.each do |tanet| %>
      <tr>
        <td><%= tanet.data %></td>
        <td><%= link_to 'Show', tanet %></td>
        <td><%= link_to 'Edit', edit_tanet_path(tanet) %></td>
        <td><%= link_to 'Destroy', tanet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tanet', new_tanet_path %>

getova/webinterface/app/views/tanets/new.html.erb
<h1>New tanet</h1>

<%= render 'form' %>

<%= link_to 'Back', tanets_path %>

getova/webinterface/app/views/tanets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @tanet.data %>
</p>

<%= link_to 'Edit', edit_tanet_path(@tanet) %> |
<%= link_to 'Back', tanets_path %>