getova/webinterface/config/routes.rb
Rails.application.routes.draw do

  resources :tanet_linkedins
  get '/scrape_linkedin' => 'tanet_linkedins#scrape_person'

  resources :tenders

  resources :complus

  post 'fetch_led_company' => 'complus#fetch_led_company'

  resources :tanets

  resources :individual_formats

  get 'companies/run_clustering' => 'companies#run_clustering'
  get 'companies/search/:search' => 'companies#search'
  get 'companies/clustering_visual' => 'companies#get_json_for_d3'

  get 'tanet' => 'tanets#index'
  get 'tanet/:id' => 'tanets#show'

  resources :companies

  resources :representations

  resources :individuals

  root 'individuals#index'

  get 'about' => 'about#index'
  get 'search' => 'search#index'

  get 'individuals/:id/:format' => 'individuals#get_format'

end

getova/webinterface/app/models/complu.rb
class Complu < ActiveRecord::Base
end

getova/webinterface/app/controllers/complus_controller.rb
class ComplusController < ApplicationController
  before_action :set_complu, only: [:show, :edit, :update, :destroy]

  # GET /complus
  # GET /complus.json
  def index
    @complus = Complu.all
  end

  # GET /complus/1
  # GET /complus/1.json
  def show
  end

  # GET /complus/new
  def new
    @complu = Complu.new
  end

  # GET /complus/1/edit
  def edit
  end

  # GET /fetch_led_company
  def fetch_led_company
    file = params[:html_data]


    puts "html_data: #{file}"

    uploaded_io = file
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end

    file_location = Rails.root.join('public', 'uploads', uploaded_io.original_filename)

    extractor = LEDExtraction::CompanyExtractor.new

    extractor.start(
      extractor_name: "Complus LED",
      files: [file_location.to_s],
      send_data_to_server: false,
      store_data_locally: false
    )

    @complu = Complu.create
    @complu.data = extractor.return_usdl
    puts @complu.to_json
    @complu.save

    respond_to do |format|
      format.html{
        if @complu.save!
          redirect_to @complu, notice: 'LED-Company was successfully fetched.'
        else
          redirect_to @complu, notice: @complu.errors
        end
      }
      format.xml { render xml: @complu }
    end

  end

  # POST /complus
  # POST /complus.json
  def create
    @complu = Complu.new(complu_params)

    respond_to do |format|
      if @complu.save
        format.html { redirect_to @complu, notice: 'LED-Company was successfully created.' }
        format.json { render :show, status: :created, location: @complu }
      else
        format.html { render :new }
        format.json { render json: @complu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /complus/1
  # PATCH/PUT /complus/1.json
  def update
    respond_to do |format|
      if @complu.update(complu_params)
        format.html { redirect_to @complu, notice: 'Complu was successfully updated.' }
        format.json { render :show, status: :ok, location: @complu }
      else
        format.html { render :edit }
        format.json { render json: @complu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complus/1
  # DELETE /complus/1.json
  def destroy
    @complu.destroy
    respond_to do |format|
      format.html { redirect_to complus_url, notice: 'Complu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_complu
    @complu = Complu.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def complu_params
    params.require(:complu).permit(:data)
  end
end

getova/webinterface/app/helpers/complus_helper.rb
module ComplusHelper
end

getova/webinterface/app/views/complus/_form.html.erb
<%= form_for(@complu) do |f| %>
  <% if @complu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@complu.errors.count, "error") %> prohibited this complu from being saved:</h2>

      <ul>
      <% @complu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br>
    <%= f.text_field :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

getova/webinterface/app/views/complus/edit.html.erb
<h1>Editing complu</h1>

<%= render 'form' %>

<%= link_to 'Show', @complu %> |
<%= link_to 'Back', complus_path %>

getova/webinterface/app/views/complus/index.html.erb
<h1>Extact data from Led-info.de </h1>
<table>
  <thead>
    <tr>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <p style="font-size: 2em"> Upload downloaded webpage from http://led-info.de/</p> 
    <%= form_tag("/fetch_led_company",action: "upload", method: "post", multipart: true) do %>
      <%= file_field_tag 'html_data' %>
      <p>
      <input name="Upload LED-Technik HTML" type="submit" />
      </p>
    <% end %>

    <% @complus.each do |complu| %>
      <tr>
        <td><%= complu.data[0..500] %></td>
        <td><%= link_to 'Show', complu %></td>
        <td><%= link_to 'Edit', edit_complu_path(complu) %></td>
        <td><%= link_to 'Destroy', complu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

getova/webinterface/app/views/complus/new.html.erb
<h1>New complu</h1>

<%= render 'form' %>

<%= link_to 'Back', complus_path %>

getova/webinterface/app/views/complus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @complu.data %>
</p>

<%= link_to 'Edit', edit_complu_path(@complu) %> |
<%= link_to 'Back', complus_path %>