getova/webinterface/config/routes.rb
Rails.application.routes.draw do

  resources :tanet_linkedins
  get '/scrape_linkedin' => 'tanet_linkedins#scrape_person'

  resources :tenders

  resources :complus

  post 'fetch_led_company' => 'complus#fetch_led_company'

  resources :tanets

  resources :individual_formats

  get 'companies/run_clustering' => 'companies#run_clustering'
  get 'companies/search/:search' => 'companies#search'
  get 'companies/clustering_visual' => 'companies#get_json_for_d3'

  get 'tanet' => 'tanets#index'
  get 'tanet/:id' => 'tanets#show'

  resources :companies

  resources :representations

  resources :individuals

  root 'individuals#index'

  get 'about' => 'about#index'
  get 'search' => 'search#index'

  get 'individuals/:id/:format' => 'individuals#get_format'

end

getova/webinterface/app/models/tanet_linkedin.rb
class TanetLinkedin < ActiveRecord::Base
  validate :data, uniqueness: true
end

getova/webinterface/app/controllers/tanet_linkedins_controller.rb
class TanetLinkedinsController < ApplicationController
  before_action :set_tanet_linkedin, only: [:show, :edit, :update, :destroy]

  # GET /tanet_linkedins
  # GET /tanet_linkedins.json
  def index
    @tanet_linkedins = TanetLinkedin.all
  end

  # GET /tanet_linkedins/1
  # GET /tanet_linkedins/1.json
  def show
  end

  # GET /tanet_linkedins/new
  def new
    @tanet_linkedin = TanetLinkedin.new
  end

  # GET /tanet_linkedins/1/edit
  def edit
  end

  # GET /scrape_linkedin
  def scrape_person
    url = params[:url]

    profile = Linkedin::Profile.get_profile(url)
    @tanet_linkedin = TanetLinkedin.new
    @tanet_linkedin.name = profile.name
    @tanet_linkedin.data = profile.to_json

    respond_to do |format|
      if @tanet_linkedin.save
        format.html { redirect_to @tanet_linkedin, notice: "#{@tanet_linkedin.name} Linkedin was successfully scraped." }
        format.json { render json: @tanet_linkedin, status: :created}
      else
        format.html { render :new }
        format.json { render json: @tanet_linkedin.errors, status: :unprocessable_entity }
      end
    end

  end

  # POST /tanet_linkedins
  # POST /tanet_linkedins.json
  def create
    @tanet_linkedin = TanetLinkedin.new(tanet_linkedin_params)

    respond_to do |format|
      if @tanet_linkedin.save
        format.html { redirect_to @tanet_linkedin, notice: 'Tanet linkedin was successfully created.' }
        format.json { render :show, status: :created, location: @tanet_linkedin }
      else
        format.html { render :new }
        format.json { render json: @tanet_linkedin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tanet_linkedins/1
  # PATCH/PUT /tanet_linkedins/1.json
  def update
    respond_to do |format|
      if @tanet_linkedin.update(tanet_linkedin_params)
        format.html { redirect_to @tanet_linkedin, notice: 'Tanet linkedin was successfully updated.' }
        format.json { render :show, status: :ok, location: @tanet_linkedin }
      else
        format.html { render :edit }
        format.json { render json: @tanet_linkedin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tanet_linkedins/1
  # DELETE /tanet_linkedins/1.json
  def destroy
    @tanet_linkedin.destroy
    respond_to do |format|
      format.html { redirect_to tanet_linkedins_url, notice: 'Tanet linkedin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tanet_linkedin
      @tanet_linkedin = TanetLinkedin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tanet_linkedin_params
      params.require(:tanet_linkedin).permit(:name, :data)
    end
end

getova/webinterface/app/helpers/tanet_linkedins_helper.rb
module TanetLinkedinsHelper
end

getova/webinterface/app/views/tanet_linkedins/_form.html.erb
<%= form_for(@tanet_linkedin) do |f| %>
  <% if @tanet_linkedin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tanet_linkedin.errors.count, "error") %> prohibited this tanet_linkedin from being saved:</h2>

      <ul>
      <% @tanet_linkedin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.text_field :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

getova/webinterface/app/views/tanet_linkedins/edit.html.erb
<h1>Editing tanet_linkedin</h1>

<%= render 'form' %>

<%= link_to 'Show', @tanet_linkedin %> |
<%= link_to 'Back', tanet_linkedins_path %>

getova/webinterface/app/views/tanet_linkedins/index.html.erb
<h1>Tanet LinkedIn Use-Case</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   <tr>
     <% randomlinkedin = ["https://www.linkedin.com/in/ioantoma", "https://www.linkedin.com/pub/benjamin-hiltpolt/" ] %>
      <%= form_tag("/scrape_linkedin", method: "get") do %>
        <%= text_field_tag 'url', randomlinkedin.sample, size: 150 %>
        <%=  'Scrape and import LinkedIn profiles' %>
        <input name="Submit_Linkedin" type="submit" />
      <% end %>
   </tr>

    <% @tanet_linkedins.each do |tanet_linkedin| %>
      <tr>
        <td><%= tanet_linkedin.name %></td>
        <td><%= tanet_linkedin.data[0..100] %></td>
        <td><%= link_to 'Show', tanet_linkedin %></td>
        <td><%= link_to 'Edit', edit_tanet_linkedin_path(tanet_linkedin) %></td>
        <td><%= link_to 'Destroy', tanet_linkedin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

getova/webinterface/app/views/tanet_linkedins/new.html.erb
<h1>New tanet_linkedin</h1>

<%= render 'form' %>

<%= link_to 'Back', tanet_linkedins_path %>

getova/webinterface/app/views/tanet_linkedins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tanet_linkedin.name %>
</p>

<p>
  <strong>Data:</strong>
  <%= @tanet_linkedin.data %>
</p>

<%= link_to 'Edit', edit_tanet_linkedin_path(@tanet_linkedin) %> |
<%= link_to 'Back', tanet_linkedins_path %>