getova/webinterface/config/routes.rb
Rails.application.routes.draw do

  resources :tanet_linkedins
  get '/scrape_linkedin' => 'tanet_linkedins#scrape_person'

  resources :tenders

  resources :complus

  post 'fetch_led_company' => 'complus#fetch_led_company'

  resources :tanets

  resources :individual_formats

  get 'companies/run_clustering' => 'companies#run_clustering'
  get 'companies/search/:search' => 'companies#search'
  get 'companies/clustering_visual' => 'companies#get_json_for_d3'

  get 'tanet' => 'tanets#index'
  get 'tanet/:id' => 'tanets#show'

  resources :companies

  resources :representations

  resources :individuals

  root 'individuals#index'

  get 'about' => 'about#index'
  get 'search' => 'search#index'

  get 'individuals/:id/:format' => 'individuals#get_format'

end

getova/webinterface/app/models/tender.rb
class Tender < ActiveRecord::Base
end

getova/webinterface/app/controllers/tenders_controller.rb
class TendersController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_tender, only: [:show, :edit, :update, :destroy]

  # GET /tenders
  # GET /tenders.json
  def index
    @tenders = Tender.all
  end

  # GET /tenders/1
  # GET /tenders/1.json
  def show
  end

  # GET /tenders/new
  def new
    @tender = Tender.new
  end

  # GET /tenders/1/edit
  def edit
  end

  # POST /tenders
  # POST /tenders.json
  def create
    @tender = Tender.new(tender_params)

    respond_to do |format|
      if @tender.save
        format.html { redirect_to @tender, notice: 'Tender was successfully created.' }
        format.json { render :show, status: :created, location: @tender }
      else
        format.html { render :new }
        format.json { render json: @tender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tenders/1
  # PATCH/PUT /tenders/1.json
  def update
    respond_to do |format|
      if @tender.update(tender_params)
        format.html { redirect_to @tender, notice: 'Tender was successfully updated.' }
        format.json { render :show, status: :ok, location: @tender }
      else
        format.html { render :edit }
        format.json { render json: @tender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenders/1
  # DELETE /tenders/1.json
  def destroy
    @tender.destroy
    respond_to do |format|
      format.html { redirect_to tenders_url, notice: 'Tender was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tender
      @tender = Tender.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tender_params
    puts "hello: #{params}"
      params.require(:tender).permit(:data)
    end
end

getova/webinterface/app/helpers/tenders_helper.rb
module TendersHelper
end

getova/webinterface/app/views/tenders/_form.html.erb
<%= form_for(@tender) do |f| %>
  <% if @tender.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tender.errors.count, "error") %> prohibited this tender from being saved:</h2>

      <ul>
      <% @tender.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br>
    <%= f.text_field :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

getova/webinterface/app/views/tenders/edit.html.erb
<h1>Editing tender</h1>

<%= render 'form' %>

<%= link_to 'Show', @tender %> |
<%= link_to 'Back', tenders_path %>

getova/webinterface/app/views/tenders/index.html.erb
<h1>Listing tenders</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tenders.each do |tender| %>
      <tr>
        <td><%= tender.data %></td>
        <td><%= link_to 'Show', tender %></td>
        <td><%= link_to 'Edit', edit_tender_path(tender) %></td>
        <td><%= link_to 'Destroy', tender, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tender', new_tender_path %>

getova/webinterface/app/views/tenders/new.html.erb
<h1>New tender</h1>

<%= render 'form' %>

<%= link_to 'Back', tenders_path %>

getova/webinterface/app/views/tenders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @tender.data %>
</p>

<%= link_to 'Edit', edit_tender_path(@tender) %> |
<%= link_to 'Back', tenders_path %>